# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cc80fd83aeb8c80ca2c5a5cc7582c3cd998365152a3350b94b55ea776d2c95412bf8e8be45627ddcf817cf09327187f12f8fbe40c21c7d8c61e8c9f250c7d10

test:
  secret_key_base: a972642ce42878535acce6a2e44ac678723f20be87e193b7a40081c7dc37207f9e2d23bbad6cf31e7302b6f891d4708eacf96d5a0f75e7f2b191d875ce197c77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
